#!/bin/bash

set -x

if [[ -n "$1" ]]
then
    ver="$1"
else
    ver="<DEV>"
fi
version="$ver ($(date --iso))"

use_mod=
use_mod="$use_mod --use=Log::Any"
use_mod="$use_mod --use=Module::CPANfile"
use_mod="$use_mod --use=Devel::CheckLib"

find . -name '*~' -delete

dev/plx fatpack trace $use_mod bin/ledgersmb-installer
dev/plx fatpack packlists-for `cat fatpacker.trace` > packlists
dev/plx fatpack tree `cat packlists`
find fatlib/ -name '.packlist' -o -name '.*' -delete -o -name '*.pod' -delete
dev/plx fatpack file bin/ledgersmb-installer > packed
sed -i -e "s/version CLONED/version $version/" packed
