#!/bin/bash

set -x

use_mod=
# these modules are auto-detected:
#  use_mod="$use_mod --use=Log::Any"
#  use_mod="$use_mod --use=Module::CPANfile"

dev/plx fatpack trace $use_mod bin/ledgersmb-installer
dev/plx fatpack packlists-for `cat fatpacker.trace` > packlists
dev/plx fatpack tree `cat packlists`
find fatlib/ -name '.*' -delete -o -name '*.pod' -delete
dev/plx fatpack file bin/ledgersmb-installer > packed


