#!/bin/bash

wget https://raw.githubusercontent.com/shadowcat-mst/plx/master/bin/plx-packed -O dev/plx
chmod +x dev/plx
dev/plx --init
dev/plx --cpanm -Ldevel --notest --with-develop --with-configure --installdeps .
