#!/bin/bash -x

scp -4 packed lsmb-uploader@get.ledgersmb.org:/www/vhosts/get.ledgersmb.org/public_html/lsmb-installer
scp -4 packed lsmb-uploader@get.ledgersmb.org:/www/vhosts/get.ledgersmb.org/public_html/ledgersmb-installer
scp -4 docs/README.html lsmb-uploader@get.ledgersmb.org://www/vhosts/get.ledgersmb.org/public_html/index.html
scp -4 docs/README.html lsmb-uploader@get.ledgersmb.org://www/vhosts/get.ledgersmb.org/public_html/README.html

