#!/bin/bash

scp packed lsmb-uploader@get.ledgersmb.org:/www/vhosts/get.ledgersmb.org/public_html/index.txt
scp docs/README.html lsmb-uploader@get.ledgersmb.org://www/vhosts/get.ledgersmb.org/public_html/README.html

