ARG SRC=fedora:35
FROM fedora:41

ARG VERSION=1.12.4
ARG USER_MODE=ROOT

RUN dnf install -q -y perl util-linux sudo

COPY ledgersmb-installer /usr/bin/ledgersmb-installer
COPY run-install /usr/bin/run-install
RUN cd /srv ; run-install
