FROM registry.suse.com/bci/bci-base:15.7

ARG VERSION=1.9.30
ARG USER_MODE=ROOT

RUN zypper refresh && zypper install -y perl perl-IO-Socket-SSL patterns-devel-base-devel_basis libpq5 postgresql-devel postgresql17-server-devel libxml2-2 libxml2-devel texlive-latex texlive-plain libgmp10 gmp-devel libexpat1 libexpat-devel util-linux sudo

COPY ledgersmb-installer /usr/bin/ledgersmb-installer
COPY run-install /usr/bin/run-install
RUN cd /srv ; run-install
