ARG SRC=fedora:35
FROM fedora:41

ARG VERSION=1.12.4

RUN dnf install -q -y perl

COPY ledgersmb-installer /usr/bin/ledgersmb-installer
RUN cd /srv ; ledgersmb-installer install --yes --no-verify-sig --log-level=trace $VERSION
