name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
    types: [opened, reopened, synchronize]

jobs:
  cancel-prior:
    if: github.repository != 'ledgersmb/LedgerSMB' || startsWith(github.ref, 'refs/pull')
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - osVariant: debian
            osImage: debian:bookworm-slim
            userMode: ROOT
          - osVariant: debian
            osImage: ubuntu:noble
            userMode: ROOT
          - osVariant: fedora
            osImage: fedora:41
            userMode: ROOT
          - osVariant: fedora
            osImage: registry.access.redhat.com/ubi8/ubi:8.1
            userMode: ROOT

          # Non-system Perl on a supported O/S (latest Perl; latest Debian)
          - osVariant: debian
            osImage: perl:latest
            userMode: ROOT

            # this uses OpenSUSE as 'unknown' linux variant
          - osVariant: unknown
            osImage: unknown
            userMode: ROOT

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
        with:
          install-modules-with: cpm
          install-modules-args: --with-develop --with-configure

      - name: Run installation
        run: |
          set -xe -o pipefail
          dev/build
          cp packed docker/ledgersmb-installer
          chmod +x docker/ledgersmb-installer
          docker build --progress=plain \
                       --build-arg SRC=${{ matrix.osImage }} \
                       --build-arg USER_MODE=${{ matrix.userMode }} \
                       -f docker/Dockerfile.${{ matrix.osVariant }} ./docker/
